version: "3"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build: ./api
    expose:
      - "4000"
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails db:migrate && 
      bundle exec rails db:seed && 
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4000:4000"
    env_file:
      - ".env"
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  web:
    build: ./web
    command: npm run start
    tty: true
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
      - postgres
