version: "3"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build: ./api
    expose:
      - "3010"
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails db:migrate && 
      bundle exec rails db:seed && 
      bundle exec rails s -p 3010 -b '0.0.0.0'"
    ports:
      - "3010:3010"
    env_file:
      - ".env"
    depends_on:
      - postgres
    tty: true
    stdin_open: true
